name: Call-Reusable BlazorApp to Azure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  call-build:
    name: Build via Reusable Workflow
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: call-build
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.mywebapp_Name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
